version: '3.3'

services:
  kontaktregister-statistikk-klient:
    image: ${REGISTRY}/kontaktregister-statistikk-klient:${VERSION}
    ports:
      - "8086:8080"
    configs:
      - source: kontaktregister-properties
        target: /application.properties
    secrets:
      - source: kontaktregister-maskinporten.cer
        target: maskinporten.cer
      - source: kontaktregister-maskinporten-private.pem
        target: maskinporten-private.pem
    networks:
      - net
      - statistics-api_net

networks:
  net:
    driver: overlay
  statistics-api_net:
    external: true

secrets:
  kontaktregister-maskinporten.cer:
    external: true
  kontaktregister-maskinporten-private.pem:
    external: true

configs:
  kontaktregister-properties:
    external: true
